eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/stretch/eureka/
server:
  port: 8899
  ip: localhost
token:
  client_id: client_1
  type: client_credentials
  scope: select
  client_secret: 123456
  url: http://localhost:8082/oauth/token
spring:
  application:
    name: appmodule
  cloud:
      client:
        ipAddress: localhost
  #数据库配置mysql
  datasource:
    url: jdbc:mysql://182.92.82.3/ai_studio?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    cache: false
##自定义文件地址配置##
file:
  address: /user/hadoop
