server:
  port: 8077

eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8081/stretch/eureka/

spring:
  cloud:
      client:
        ipAddress: localhost
  application:
    name: machflow

#pyserver:
#  url: http://localhost
#  port: 3001







