#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:8081/stretch/eureka/
server:
  port: 8080
  ip: localhost
#spring:
 # application:
    #name: workflow
pyserver:
  url: http://localhost
  port: 3001

#监听类型
listener:
  type: executionListener





