server:
  port: 8077
  ip: localhost

eureka:
 client:
   serviceUrl:
     defaultZone: http://47.105.127.125:8081/stretch/eureka/

spring:
  cloud:
    client:
      ipAddress: localhost
  application:
    name: machflow
  datasource:
    url: jdbc:mysql://182.92.82.3:3306/ai_studio?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    cache: false
  server:
    MaxFileSize: 1024MB
    MaxRequestSize: 1500MB

#pyserver:
#  url: http://localhost
#  port: 3001
hadoop:
  url: hdfs://47.105.127.125
  port: 9000
  defaultFs: fs.defaultFS
  host: hdfs://47.105.127.125:9000






