server:
  port: 5679
spring:
  application:
    name: pipe
sidecar:
  port: 3001
  health-uri: http://localhost:${sidecar.port}/health
logging:
  level:
    org.springframework.web: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/stretch/eureka/
