server:
  port: 5678
spring:
  application:
    name: py-sidecar
sidecar:
  port: 8000
  health-uri: http://localhost:${sidecar.port}}/health
eureka
  client
    serviceUrl
      defaultZone=http://localhost:8000/eureka/
