eureka:
  client:
    serviceUrl:
      defaultZone: http://182.92.82.3:8081/stretch/eureka/
server:
  port: 7777
  ip: localhost
token:
  client_id: client_1
  type: client_credentials
  scope: select
  client_secret: 123456
  url: http://localhost:8082/oauth/token
spring:
  application:
    name: dataset
  cloud:
    client:
      ipAddress: localhost
  #数据库配置mysql
  primary:
    url: jdbc:mysql://182.92.82.3/ai_studio?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  secondary:
    url: jdbc:mysql://182.92.82.3:3306/hive_91?createDatabaseIfNotExist=true
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
####hive数据源配置#####
hive:
  url: jdbc:hive2://182.92.82.3
  port: 10000
  schema: default
  driver-name: org.apache.hive.jdbc.HiveDriver
  user:
  password:
##hive表在hadoop中路径配置##
hadoop:
  url: hdfs://182.92.82.3
  port: 8020



