eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8051/stretch/eureka/
server:
  port: 7777
  ip: localhost
token:
  client_id: client_1
  type: client_credentials
  scope: select
  client_secret: 123456
  url: http://localhost:8052/oauth/token
spring:
  application:
    name: dataset
  cloud:
    client:
      ipAddress: localhost
  #数据库配置mysql
  dataset_jdbc:
    url: jdbc:mysql://182.92.82.3:3306/ai_studio?useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://172.16.31.91/ai_studio?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111
#    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  hivedata_jdbc:
    url: jdbc:mysql://182.92.82.3:3306/hive_ali2?createDatabaseIfNotExist=true
#    url: jdbc:mysql://172.16.31.234:3306/hive_91?createDatabaseIfNotExist=true
    username: root
    password: 111111
#    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
#  redis配置
  redis:
    host: 47.105.127.125
    database: 0
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    timeout: 2000
    password:
####hive数据源配置#####
hive:
  url: jdbc:hive2://47.105.127.125
#  url: jdbc:hive2://172.16.31.91
  port: 10000
  schema: default
  driver-name: org.apache.hive.jdbc.HiveDriver
  user:
  password:
##hive表在hadoop中路径配置##
hadoop:
  url: hdfs://47.105.127.125
  port: 9000



