server:
  port: 5678
spring:
  application:
    name: mining
sidecar:
  port: 3002
  health-uri: http://localhost:${sidecar.port}/health
logging:
  level:
    org.springframework.web: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8051/stretch/eureka/
